///////////////////////////////////////////////////@file NppPluginResource.cpp
///
/// Notepad++ Plugin Configuration.
///
/// Generated by: rc2cpp.bat from NppPluginResource.rc
///
///                                                                23/02/2018
///
//////////////////////////////////////////////////////////////////////////////
#include <string.h>
#include <windows.h>
#include "NppPluginResource.hpp" 
#include "SettingsDlg.h" 
const TCHAR NPP_PLUGIN_NAME[] = TEXT("Test"); 
const *TCHAR NPP_PROJECT_NAME = NULL; 
ENVVAR ENVVAR_Tools_Environment[] =
{ 
    { ID_PLKEXE_FBOX, -1, ID_PLKEXE_BTTN, "PLKEXE", NULL, NULL },
    { ID_NCTEXE_FBOX, -1, ID_NCTEXE_BTTN, "NCTEXE", NULL, NULL },
    { ID_CRLEXE_FBOX, -1, ID_CRLEXE_BTTN, "CRLEXE", NULL, NULL },
    { ID_VBMEXE_FBOX, -1, ID_VBMEXE_BTTN, "VBMEXE", NULL, NULL },
    { ID_ZIPEXE_FBOX, -1, ID_ZIPEXE_BTTN, "ZIPEXE", NULL, NULL },
    { ID_NPPEXE_CBOX, -1, -1, "NPPEXE", NULL, NULL },
    { ID_DEVCOM_CBOX, -1, -1, "DEVCOM", NULL, NULL },
    { ID_QMDLST_CBOX, -1, -1, "QMDLST", NULL, NULL },
    { ID_NMDLST_CBOX, -1, -1, "NMDLST", NULL, NULL },
    { ID_IMDLST_CBOX, -1, -1, "IMDLST", NULL, NULL },
    { ID_AMDLST_CBOX, -1, -1, "AMDLST", NULL, NULL },
    { ID_DSPMOD_CBOX, -1, -1, "DSPMOD", NULL, NULL },
    { ID_INTMOD_CBOX, -1, -1, "INTMOD", NULL, NULL },
    { ID_ISSDBG_CBOX, -1, -1, "ISSDBG", NULL, NULL },
    { ID_ISSFIN_CBOX, -1, -1, "ISSFIN", NULL, NULL },
    { ID_ISSPRC_CBOX, -1, -1, "ISSPRC", NULL, NULL },
    { ID_ISSPRD_CBOX, -1, -1, "ISSPRD", NULL, NULL },
    { ID_SVNLOG_CBOX, -1, -1, "SVNLOG", NULL, NULL },
    { ID_SVNCKO_CBOX, -1, -1, "SVNCKO", NULL, NULL },
    { ID_SVNEOL_CBOX, -1, -1, "SVNEOL", NULL, NULL },
    { ID_SVNLST_CBOX, -1, -1, "SVNLST", NULL, NULL },
    { ID_SVNLTT_CBOX, -1, -1, "SVNLTT", NULL, NULL },
    { ID_TAGDEF_CBOX, -1, -1, "TAGDEF", NULL, NULL },
    { ID_TAGNUL_CBOX, -1, -1, "TAGNUL", NULL, NULL },
    { -1, -1, -1, NULL, NULL, NULL }
}; 
const int nbFunc = 1; 
FuncItem funcItem[nbFunc]; 
ENVSET envsetlst[] = 
{ 
    { TEXT("Tools Environment"), SettingsDlg(IDD_Tools_Environment, ENVVAR_Tools_Environment) }, 
}; 
