///////////////////////////////////@file NppPluginBuildEnvironmentResource.cpp
///
/// Notepad++ Tools Environment Configuration.
///
/// Generated by: rc2cpp.bat from NppPluginBuildEnvironmentResource.rc
///
///                                                                16 Feb 2018
///
//////////////////////////////////////////////////////////////////////////////
#include "NppPluginBuildEnvironmentResource.hpp" 
#include "SettingsDlg.h" 
const TCHAR NPP_PLUGIN_NAME[] = TEXT("Build Environment"); 
ENVVAR ENVVAR_Build_Settings[] =
{ 
    { ID_BLDFIL_FBOX, -1, ID_BLDFIL_BTTN, "BLDFIL", NULL, NULL },
    { ID_BLDBRA_CBOX, -1, -1, "BLDBRA", NULL, NULL },
    { ID_BLDUSR_CBOX, -1, -1, "BLDUSR", NULL, NULL },
    { ID_BLDPWD_CBOX, -1, -1, "BLDPWD", NULL, NULL },
    { ID_BLDADR_CBOX, -1, -1, "BLDADR", NULL, NULL },
    { ID_BLDVER_CBOX, -1, -1, "BLDVER", NULL, NULL },
    { ID_BLDTGT_CBOX, -1, -1, "BLDTGT", NULL, NULL },
    { ID_BLDPRJ_CBOX, -1, -1, "BLDPRJ", NULL, NULL },
    { ID_BLDPFM_CBOX, -1, -1, "BLDPFM", NULL, NULL },
    { ID_BLDOUT_CBOX, -1, -1, "BLDOUT", NULL, NULL },
    { ID_TGTUSR_CBOX, -1, -1, "TGTUSR", NULL, NULL },
    { ID_TGTPWD_CBOX, -1, -1, "TGTPWD", NULL, NULL },
    { ID_TGTADR_CBOX, -1, -1, "TGTADR", NULL, NULL },
    { ID_DBSHAN_FBOX, -1, ID_DBSHAN_BTTN, "DBSHAN", NULL, NULL },
    { -1, -1, -1, NULL, NULL, NULL }
}; 
ENVVAR ENVVAR_Directory_Settings[] =
{ 
    { ID_DIRFIL_FBOX, -1, ID_DIRFIL_BTTN, "DIRFIL", NULL, NULL },
    { ID_PRJDIR_DBOX, ID_PRJDIR_BTTN, -1, "PRJDIR", NULL, "PRJDRV" },
    { ID_TMPDIR_DBOX, ID_TMPDIR_BTTN, -1, "TMPDIR", NULL, "TMPDRV" },
    { ID_TLSDIR_DBOX, ID_TLSDIR_BTTN, -1, "TLSDIR", NULL, "TLSDRV" },
    { ID_BATDIR_DBOX, ID_BATDIR_BTTN, -1, "BATDIR", NULL, "BATDRV" },
    { ID_TGZDIR_DBOX, ID_TGZDIR_BTTN, -1, "TGZDIR", NULL, "TGZDRV" },
    { ID_RELDIR_DBOX, ID_RELDIR_BTTN, -1, "RELDIR", NULL, "RELDRV" },
    { ID_CYGDIR_DBOX, ID_CYGDIR_BTTN, -1, "CYGDIR", NULL, "CYGDRV" },
    { ID_FFSDIR_DBOX, ID_FFSDIR_BTTN, -1, "FFSDIR", NULL, "FFSDRV" },
    { ID_MAPDRV_CBOX, -1, -1, "MAPDRV", NULL, NULL },
    { ID_HOMDRV_CBOX, -1, -1, "HOMDRV", NULL, NULL },
    { -1, -1, -1, NULL, NULL, NULL }
}; 
ENVVAR ENVVAR_Executable_Settings[] =
{ 
    { ID_EXEFIL_FBOX, -1, ID_EXEFIL_BTTN, "EXEFIL", NULL, NULL },
    { ID_TTLEXE_FBOX, -1, ID_TTLEXE_BTTN, "TTLEXE", NULL, NULL },
    { ID_PLKEXE_FBOX, -1, ID_PLKEXE_BTTN, "PLKEXE", NULL, NULL },
    { ID_PCPEXE_FBOX, -1, ID_PCPEXE_BTTN, "PCPEXE", NULL, NULL },
    { ID_PYTEXE_FBOX, -1, ID_PYTEXE_BTTN, "PYTEXE", NULL, NULL },
    { ID_FFSEXE_FBOX, -1, ID_FFSEXE_BTTN, "FFSEXE", NULL, NULL },
    { ID_BEGCMD_CBOX, -1, -1, "BEGCMD", NULL, NULL },
    { ID_TRMCMD_CBOX, -1, -1, "TRMCMD", NULL, NULL },
    { -1, -1, -1, NULL, NULL, NULL }
}; 
ENVVAR ENVVAR_Miscellaneous_Settings[] =
{ 
    { ID_MSCFIL_FBOX, -1, ID_MSCFIL_BTTN, "MSCFIL", NULL, NULL },
    { ID_DBSDIR_CBOX, -1, -1, "DBSDIR", NULL, NULL },
    { ID_DBSFIL_CBOX, -1, -1, "DBSFIL", NULL, NULL },
    { ID_LTZCON_CBOX, -1, -1, "LTZCON", NULL, NULL },
    { ID_LTZCIT_CBOX, -1, -1, "LTZCIT", NULL, NULL },
    { ID_LOGDIR_CBOX, -1, -1, "LOGDIR", NULL, NULL },
    { ID_LOGFIL_CBOX, -1, -1, "LOGFIL", NULL, NULL },
    { ID_MOVLOG_CBOX, -1, -1, "MOVLOG", NULL, NULL },
    { -1, -1, -1, NULL, NULL, NULL }
}; 
ENVVAR ENVVAR_SQL_Settings[] =
{ 
    { ID_SQLFIL_FBOX, -1, ID_SQLFIL_BTTN, "SQLFIL", NULL, NULL },
    { -1, -1, -1, NULL, NULL, NULL }
}; 
ENVVAR ENVVAR_Custom_Settings[] =
{ 
    { ID_CSTFIL_FBOX, -1, ID_CSTFIL_BTTN, "CSTFIL", NULL, NULL },
    { -1, -1, -1, NULL, NULL, NULL }
}; 
const int nbFunc = 6; 
FuncItem funcItem[nbFunc]; 
ENVSET envsetlst[] = 
{ 
    { TEXT("Build Settings"), SettingsDlg(IDD_Build_Settings, ENVVAR_Build_Settings) }, 
    { TEXT("Directory Settings"), SettingsDlg(IDD_Directory_Settings, ENVVAR_Directory_Settings) }, 
    { TEXT("Executable Settings"), SettingsDlg(IDD_Executable_Settings, ENVVAR_Executable_Settings) }, 
    { TEXT("Miscellaneous Settings"), SettingsDlg(IDD_Miscellaneous_Settings, ENVVAR_Miscellaneous_Settings) }, 
    { TEXT("SQL Settings"), SettingsDlg(IDD_SQL_Settings, ENVVAR_SQL_Settings) }, 
    { TEXT("Custom Settings"), SettingsDlg(IDD_Custom_Settings, ENVVAR_Custom_Settings) }, 
}; 
