@echo off
for /f "tokens=1,2,3 delims=/" %%a in ("%~t0") do (set day=%%a && set /a month=%%b && set year=%%c)
for /f "tokens=%month%" %%a in ("Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec") do set month=%%a
echo #########################################################################
echo ###  _     _                                                          ###
echo ### ^| ^|   ^| ^|___ _   ___ ___  ___ _ __  ___                           ###
echo ### ^| ^| _ ^| / _ \ ^| ^| __/ _ \^|__ \ '_ \/ _ \                          ###
echo ### ^| ^|^| ^|^|  (_)  ^|_^| _^|\__^| / _   ^| ^| \__^| ^|                         ###
echo ### ^|___ ___\___/___^|_^| ^|___/\___/_^| ^|_^|___/                          ###
echo ###                ____                                               ###
echo ###               ^|  _ \_   _ _ __  ___  _ ___ _ __                   ###
echo ###               ^| ^| \ \^| ^| ^| '_ \/ __^|^| / _ \ '_ \                  ###
echo ###               ^| ^|_/ /^|_^| ^| ^| ^| \__ /_  (_)  ^| ^| ^|                 ###
echo ###               ^|____/\__'_^|_^| ^|_^|___\__\___/_^| ^|_^|                 ###
echo ###                                                                   ###
echo ### Copyright (c) 2016 Wolfgang Dunsdon.                              ###
echo ### All rights reserved.                                              ###
echo ###                                                                   ###
echo ###                                                       %day%%month% %year:~0,4% ###
echo ###                                                                   ###
echo ###                                                  @file %~n0%~x0 ###
echo ###                                                                   ###
echo ### @brief Generate batch file header...                              ###
echo ###                                                                   ###
echo ### @param %%1 - Target file                                           ###
echo ### @param %%2 - Target description                                    ###
echo ### @param %%3 - Parameter(s) description                              ###
echo ###                                                                   ###
echo #########################################################################
if [%1] equ [] goto :NOTGTFIL
set TGTFIL=%~1
echo ###
echo ### Writing Header to %TGTFIL%...
echo ###
echo @echo off> "%TGTFIL%"
echo for /f "tokens=1,2,3 delims=/" %%%%a in ("%%~t0") do (set day=%%%%a ^&^& set /a month=%%%%b ^&^& set year=%%%%c)>> "%TGTFIL%"
echo for /f "tokens=%%month%%" %%%%a in ("Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec") do set month=%%%%a>> "%TGTFIL%"
echo echo #########################################################################>> "%TGTFIL%"
echo echo ###                                                                   ###>> "%TGTFIL%"
echo echo ###                                                       %%day%%%%month%% %%year:~0,4%% ###>> "%TGTFIL%"
echo echo ###                                                                   ###>> "%TGTFIL%"
echo echo ###                                                  @file %%~n0%%~x0 ###>> "%TGTFIL%"
echo echo ###                                                                   ###>> "%TGTFIL%"
if [%2] equ [] (echo echo ### @brief Set build environment...                                      ###>> "%TGTFIL%"
) else (echo echo ### @brief %~2                                   ###>> "%TGTFIL%") 
echo echo ###                                                                   ###>> "%TGTFIL%"
if [%3] equ [] goto :PRMEND
set /a PRMCNT=0 
:PRMCNT
set /a PRMCNT+=1 
echo echo ### @param %%%%%PRMCNT% - %~3                              ###>> "%TGTFIL%"
shift
if [%3] neq [] goto :PRMCNT
echo echo ###                                                                   ###>> "%TGTFIL%"
:PRMEND
echo echo ### File header generated by: %~n0%~x0...                           ###>> "%TGTFIL%"
echo echo ###                                                                   ###>> "%TGTFIL%"
echo echo ### This is a generated file so beware if editing...                  ###>> "%TGTFIL%"
echo echo ###                                                                   ###>> "%TGTFIL%"
echo echo #########################################################################>> "%TGTFIL%"
goto :EOF
:NOTGTFIL
echo ###
echo ###                                                     NO Target File...
echo ###
